// <auto-generated />
using System;
using BookFlaz.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookFlaz.Infrastructure.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20251126010713_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookFlaz.Domain.Entities.Anuncio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstadoAnuncio")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EstadoLivro")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Imagens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LivroIsbn")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoAnuncio")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<long>("VendedorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("LivroIsbn");

                    b.HasIndex("VendedorId");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Avaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AvaliadoId")
                        .HasColumnType("bigint");

                    b.Property<long>("AvaliadorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estrelas")
                        .HasColumnType("int");

                    b.Property<long>("TransacaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadoId");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("TransacaoId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("NotificacoesAtivas")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<double>("ReputacaoMedia")
                        .HasColumnType("float");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Conversa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnuncioId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompradorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<long>("VendedorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("CompradorId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Conversas");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Devolucao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Confirmada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataRececaoVendedor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<long>("TransacaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("clienteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.HasIndex("clienteId");

                    b.ToTable("Devolucoes");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Favorito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnuncioId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAdicionado")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Livro", b =>
                {
                    b.Property<long>("Isbn")
                        .HasColumnType("bigint");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Isbn");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ConversaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConversaId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.MovimentoPontos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimento")
                        .HasColumnType("int");

                    b.Property<long?>("TransacaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TransacaoId");

                    b.ToTable("MovimentosPontos");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoNotificacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.PedidoTransacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnuncioId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompradorId")
                        .HasColumnType("bigint");

                    b.Property<long>("ConversaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<long>("DestinatarioId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DiasDeAluguel")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPedido")
                        .HasColumnType("int");

                    b.Property<long>("RemetenteId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoAnuncio")
                        .HasColumnType("int");

                    b.Property<double>("ValorProposto")
                        .HasColumnType("float");

                    b.Property<long>("VendedorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("CompradorId");

                    b.HasIndex("ConversaId");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("VendedorId");

                    b.ToTable("PedidosTransacao");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Transacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompradorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoTransacao")
                        .HasColumnType("int");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint");

                    b.Property<int>("PontosUsados")
                        .HasColumnType("int");

                    b.Property<double>("ValorDesconto")
                        .HasColumnType("float");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("float");

                    b.Property<long>("VendedorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.HasIndex("VendedorId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Anuncio", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroIsbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", "Vendedor")
                        .WithMany("AnunciosVendedor")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Categoria");

                    b.Navigation("Livro");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Cliente", "Avaliado")
                        .WithMany("AvaliacoesRecebidas")
                        .HasForeignKey("AvaliadoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", "Avaliador")
                        .WithMany("AvaliacoesFeitas")
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookFlaz.Domain.Entities.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliado");

                    b.Navigation("Avaliador");

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Conversa", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Anuncio", null)
                        .WithMany()
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.ClientNoAction);
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Devolucao", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Transacao", null)
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Favorito", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Anuncio", "Anuncio")
                        .WithMany("Favoritos")
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Favoritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Anuncio");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Mensagem", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookFlaz.Domain.Entities.Conversa", null)
                        .WithMany()
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.MovimentoPontos", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookFlaz.Domain.Entities.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.PedidoTransacao", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Anuncio", null)
                        .WithMany()
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookFlaz.Domain.Entities.Conversa", null)
                        .WithMany()
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BookFlaz.Domain.Entities.PedidoTransacao", null)
                        .WithOne()
                        .HasForeignKey("BookFlaz.Domain.Entities.Transacao", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookFlaz.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Anuncio", b =>
                {
                    b.Navigation("Favoritos");
                });

            modelBuilder.Entity("BookFlaz.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("AnunciosVendedor");

                    b.Navigation("AvaliacoesFeitas");

                    b.Navigation("AvaliacoesRecebidas");

                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
